# Generated by Django 4.2.7 on 2024-04-06 06:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_product_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('timedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
