# Generated by Django 4.2.7 on 2024-04-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
